trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps: 

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo '##vso[task.setvariable variable=sauce]0.0.4'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'
      feedsToUse: 'select'
      vstsFeed: $(Nuget-Feed)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'
      nobuild: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'SAUCE'
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(Nuget-Feed)'
      allowPackageConflicts: true