trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps: 
  - bash: |
      echo "##vso[task.setvariable variable=sauce]0.0.2"
  
  - bash: |
      echo "my environment variable is $SAUCE"
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: $(Nuget-Feed)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      nobuild: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'SAUCE'
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(Nuget-Feed)'
      allowPackageConflicts: true