trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps: 
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: $(Nuget-Feed)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(Nuget-Feed)'
      allowPackageConflicts: true