trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  'BUILD_NUMBER': '0.1.0'

steps: 
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        version='0.0.7'
        echo "##vso[task.setvariable variable=BUILD_NUMBER;]$(version)"
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'
      feedsToUse: 'select'
      vstsFeed: $(Nuget-Feed)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: 'KaerMorhen.SDK.Greeting/KaerMorhen.SDK.Greeting.csproj'
      nobuild: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'BUILD_NUMBER'
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(Nuget-Feed)'
      allowPackageConflicts: true